"""Live scenario planning for `setup.py inject <scenario>`."""
import datetime as _dt

from . import anomalies as _an
from . import streams as S
from .entities import EDGES, SERVICE_APP_CODE, SERVICES
from .generate import Plan, _iso, _parse, DEFAULT_SEED

_UTC = _dt.timezone.utc
_LOG_KINDS = {"failure", "log_spike", "volume_drop", "cascade", "terminal_errors"}


def _with_upstream_callers(services):
    """Affected services plus every (transitive) upstream caller.

    Downstream transactions are generated by their callers (parent spans), so regenerating and deleting
    only the affected services would drop the callers' share of the traffic (a volume dip).
    """
    out = list(services)
    changed = True
    while changed:
        changed = False
        for (caller, _tx), (callee, _i) in EDGES.items():
            if callee in out and caller not in out:
                out.append(caller)
                changed = True
    return out


def plan_inject(meta, scenario, now):
    """Returns {"anomalies": [dict], "delete": [{"stream", "range", "terms", "time_field"}],
    "plan": Plan-dict with only=..., "windows": [(start, end)], "delayed": bool}.

    `meta` is the mlws-meta document (t0, start, tail_end, seed, scale, anomalies, ...).
    Datetimes in "windows" are timezone-aware UTC; "range" values are ISO strings.
    """
    if scenario not in _an.LIVE_SCENARIOS:
        raise ValueError("unknown scenario %r (choose from %s)" % (scenario, ", ".join(sorted(_an.LIVE_SCENARIOS))))
    now = now.astimezone(_UTC)
    live = _an.LIVE_SCENARIOS[scenario](now)
    delayed = scenario == "delayed"
    services = []
    codes = []
    for a in live:
        tg = a.target
        for key in ("service", "downstream"):
            v = tg.get(key)
            if v and v not in services:
                services.append(v)
        if a.kind in _LOG_KINDS or a.kind == "delayed_logs":
            c = tg.get("app_code") or SERVICE_APP_CODE.get(tg.get("service"))
            if c and c not in codes:
                codes.append(c)
    if delayed or all(a.kind in ("log_spike", "terminal_errors", "delayed_logs") for a in live):
        # log-only scenarios leave APM streams untouched
        services = []
    else:
        services = _with_upstream_callers(services)
    start = min(a.start for a in live)
    end = max(a.end for a in live)
    # the regenerated range must not extend the plan beyond its tail
    seed = (int(meta.get("seed", DEFAULT_SEED)) * 31 + int(now.timestamp() // 60)) & 0x7FFFFFFF
    plan = Plan(t0=_parse(meta["t0"]), start=_parse(meta.get("start", meta["t0"])),
                tail_end=_parse(meta.get("tail_end", _iso(end))), seed=seed,
                scale=float(meta.get("scale", 1.0)),
                with_population=bool(meta.get("with_population", False)),
                anomalies=live, only={"services": services, "app_codes": codes})
    delete = []
    if not delayed:
        rng = [_iso(start), _iso(end)]
        for st in (S.TRACES, S.ERRORS, S.MT, S.MST, S.MSUM):
            if services:
                delete.append({"stream": st, "range": rng, "time_field": "@timestamp",
                               "terms": {"service.name": list(services)}})
        if codes:
            delete.append({"stream": S.LOGS, "range": rng, "time_field": "@timestamp",
                           "terms": {"app_code.keyword": list(codes)}})
    return {"anomalies": [a.to_dict() for a in live], "delete": delete, "plan": plan.to_dict(),
            "windows": [(start, end)], "delayed": delayed}
